name: Website

on:
  push:
    branches:
      - 'main'

jobs:
  docs:
    name: 'build gh-pages'
    runs-on: ubuntu-latest
    steps:
      # Get a Python suitable for our usage
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      # Make sure the GHA environment is sane
      - name: Setup Environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
      # Grab the website repo
      - name: Checkout Black Magic Debug Website Repo
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      # Update the host environment and make a venv for building the site
      - name: Setup Sphinx
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install graphviz python3-virtualenv
          virtualenv .env
          . .env/bin/activate
          pip3 install -U pip setuptools wheel
          pip3 install -r requirements.txt
      # Now build the website
      - name: Build
        shell: bash
        run: |
          . .env/bin/activate
          sphinx-build -b html . build
      # Deploy the resulting files
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
          keep_history: true
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
